install chrome/driver in docker

diff --git a/backend/docker/php/Dockerfile b/backend/docker/php/Dockerfile
--- a/backend/docker/php/Dockerfile
+++ b/backend/docker/php/Dockerfile
@@ -19,5 +19,69 @@ RUN echo "Y" | apt install python3-pip
 RUN pip install pandas
 RUN pip install numpy
 RUN pip install -U scikit-learn
+RUN pip install selenium
+
+
+# # download the chromedriver
+# RUN apt-get update && apt-get install -y wget unzip \
+#  && wget -q https://storage.googleapis.com/chrome-for-testing-public/121.0.6167.184/linux64/chromedriver-linux64.zip \
+#  && unzip chromedriver-linux64.zip -d /usr/local/bin \
+#  && mv /usr/local/bin/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver \
+#  && chmod +x /usr/local/bin/chromedriver \
+#  && ls /usr/local/bin
+
+# # download google
+# RUN apt-get update && apt-get install -y wget unzip gnupg2 \
+#  && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg \
+#  && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
+#  && apt-get update \
+#  && apt-get install -y google-chrome-stable
+
+# RUN set -ex; \
+#     apt-get update; \
+#     apt-get install -y gnupg wget curl unzip --no-install-recommends; \
+#     wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/google.gpg --import; \
+#     chmod 644 /etc/apt/trusted.gpg.d/google.gpg; \
+#     echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list; \
+#     apt-get update -y; \
+#     apt-get install -y google-chrome-stable; \
+#     CHROME_VERSION=$(google-chrome --product-version | grep -oE "^[0-9]+"); \
+#     CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION"); \
+#     wget -q --continue -P /chromedriver "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"; \
+#     unzip /chromedriver/chromedriver* -d /usr/local/bin/
+
+
+# FROM python:3.10.2-bullseye
+
+# Install dependencies
+RUN apt-get update -y && apt-get install -y wget xvfb unzip jq
+
+# Install Google Chrome dependencies
+RUN apt-get install -y libxss1 libappindicator1 libgconf-2-4 \
+    fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 libxtst6 lsb-release xdg-utils \
+    libgbm1 libnss3 libatk-bridge2.0-0 libgtk-3-0 libx11-xcb1 libxcb-dri3-0
+
+
+# Fetch the latest version numbers and URLs for Chrome and ChromeDriver
+RUN curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json > /tmp/versions.json
+
+RUN CHROME_URL=$(jq -r '.channels.Stable.downloads.chrome[] | select(.platform=="linux64") | .url' /tmp/versions.json) && \
+    wget -q --continue -O /tmp/chrome-linux64.zip $CHROME_URL && \
+    unzip /tmp/chrome-linux64.zip -d /opt/chrome
+
+RUN chmod +x /opt/chrome/chrome-linux64/chrome
+
+
+RUN CHROMEDRIVER_URL=$(jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform=="linux64") | .url' /tmp/versions.json) && \
+    wget -q --continue -O /tmp/chromedriver-linux64.zip $CHROMEDRIVER_URL && \
+    unzip /tmp/chromedriver-linux64.zip -d /opt/chromedriver && \
+    chmod +x /opt/chromedriver/chromedriver-linux64/chromedriver
+
+# Set up Chromedriver Environment variables
+ENV CHROMEDRIVER_DIR /opt/chromedriver
+ENV PATH $CHROMEDRIVER_DIR:$PATH
+
+# Clean upa
+RUN rm /tmp/chrome-linux64.zip /tmp/chromedriver-linux64.zip /tmp/versions.json
 
 RUN service apache2 restart
